[book]
authors = ["Slushee", "MarcBlancSans"]
language = "en"
multilingual = false
src = "src"
title = "Max Developer Guide"

[output.html]
default-theme = "coal"
git-repository-icon = "fa-github"
git-repository-url = "https://github.com/GameDEV-UPC/max"
edit-url-template = "https://github.com/GameDEV-UPC/max-developer-guide/issues"
site-url = "/max-developer-guide/"
